/* tslint:disable:max-line-length */
var app;
(function (app) {
    var trial;
    (function (trial) {
        'use strict';
        trial.trialTemplate = '<!--<form><fieldset><legend>Legend</legend><div class="form-group form-group-sm"><label for="textInput">Text Input</label><div class="input-group input-group-sm"><span class="input-group-btn"><button type="button" class="btn btn-default" ng-click="trialCtrl.open($event)"><i class="glyphicon glyphicon-calendar"></i></button></span><input type="text" id="textInput" class="form-control" placeholder="text input"><span class="input-group-addon" id="basic-addon2">@example.com</span></div></div><div class="form-group"><div class="input-group"><label for="textInput">Text Input</label><input type="text" id="textInput" class="form-control" placeholder="text input"></div></div><div class="form-group form-group-lg"><div class="input-group input-group-lg"><label for="textInput">Text Input</label><input type="text" id="textInput" class="form-control" placeholder="text input"></div></div></fieldset></form><hr/>--><trial class="container"><row class="row"><cell class="col-xs-12"><label>edit mode</label><input type="checkbox" ng-model="trialCtrl.editMode"/><label>rowspan</label><input type="number" ng-model="trialCtrl.selectedCell.rowSpan" min="1"/><label>colspan</label><input type="number" ng-model="trialCtrl.selectedCell.colSpan" min="1"/><hr/><form><table-layout edit-mode="trialCtrl.editMode"                      layout="trialCtrl.tableLayout"                      select-cell="trialCtrl.selectCell"                      allow-content="trialCtrl.allowContent"                      added-content="trialCtrl.addedContent"                      removed-content="trialCtrl.removedContent"></table-layout></form><hr/><ul><li ng-repeat="fieldSet in trialCtrl.fieldSets" draggable="true" drag-effect="\'move\'" drag-type="\'fieldset\'"            drag-data="fieldSet">          {{fieldSet.id}}</li></ul><hr/><ul><li ng-repeat="field in trialCtrl.fields" draggable="true" drag-effect="\'move\'" drag-type="\'field\'"            drag-data="field"><label>{{field.data.label}}</label><input type="text" ng-model="field.data.value"></li></ul><ul><li ng-repeat="field in trialCtrl.usedFields">          {{field.id}} - {{field.type}}</li></ul></cell></row></trial>';
    })(trial = app.trial || (app.trial = {}));
})(app || (app = {}));
//# sourceMappingURL=trial.template.html.js.map